---
title: "GDP"
author: "Joon"
date: "7/31/2020"
output: html_document
---


```{r message=FALSE}
library("DT")
library("tidyverse")
library("plotly")
library("ggplot2")
```


```{r message=FALSE}
singapore_gdp <- read_csv("SGP_GDP.csv")
```

```{r}
head(singapore_gdp)
```
```{r}
colnames(singapore_gdp)
```


```{r}
GDP_in_billionUSD <- as.numeric(as.character(singapore_gdp$GDP)) / 1000000000 %>% round(2)
```


```{r}
gdp_per_capita <- ggplot(data=singapore_gdp) +
  geom_line(mapping=aes(x=Year, y = GDP_per_capita), colour="gold") +
  geom_point(mapping=aes(x=Year, y = GDP_per_capita), size = 0.1, colour = "#000099") +
  theme(panel.background=element_blank()) +
  theme(plot.background=element_blank()) +
  theme(panel.grid.major.y=element_line(color="grey")) +
  labs(y = "GDP_per_capita in USD") +
  ggtitle("Singapore GDP_per_capita per year", subtitle = "Source: World Bank. Singapore GDP from 1960 till 2019")

fig <- ggplotly(gdp_per_capita)

fig
```


```{r}
theme_set(theme_minimal())
head(economics)
ggplot(economics, aes(x=date)) + 
  geom_line(aes(y = psavert), color = "darkred") + 
  geom_line(aes(y = uempmed), color="steelblue") 
```

```{r}
singapore_gdp2 <- read_csv("SGP_GDP2.csv")

head(singapore_gdp2)
```


```{r}

y1_max = max(singapore_gdp2$GDP_per_capita)
y2_max = max(singapore_gdp2$HDB_Resale_Price)

ay1 <- list(
  tickfont = list(color = "blue"),
  title = "GDP per Capita",
  tick0 = 0,
  range = c(0, y1_max+3811.221),
  dtick = (y1_max+3811.221)/5,
  autotick=FALSE,
  color = "blue"
)

ay2 <- list(
  tickfont = list(color = "red"),
  overlaying = "y",
  side = "right",
  title = "HDB Price",
  range = c(0,y2_max+23559),
  dtick = (y2_max+23559)/5,
  tick0 = 0,
  autotick=FALSE,
  color = "red",
  gridcolor = "lightgrey"
)


fig <- plot_ly() %>%
  add_trace(x = ~singapore_gdp2$Year, y = ~singapore_gdp2$GDP_per_capita, name = "GDP per Capita",mode = 'lines+markers') %>%
  add_trace(x = ~singapore_gdp2$Year, y = ~singapore_gdp2$HDB_Resale_Price, name = "HDB Price", yaxis = "y2",line=list(color="red", width=2),marker = list(color="red", width=2),mode = 'lines+markers') %>%
  layout(
    yaxis2 = ay2,
    yaxis = ay1,
    xaxis = list(title="Year",color="black",linecolor="lightgrey",showgrid = F,ticks = "outside",tickcolor = "lightgrey"),
    title = "Singapore Economy & HDB Resale Price",
    hovermode = "x unified")
fig <- fig %>% layout(legend = list(x = 100, y = 0.95))
fig
```


