```{r}
resale_loglat <-read_csv("data/HDB Resale data final.csv")
resale_loglat_4room_2019 <-resale_loglat %>% 
  mutate(year=substr(month, start = 1, stop = 4)) %>%
  mutate(full_address=str_to_title(full_address)) %>%
  filter(latitude_list_full != 0) %>%
  filter(year == "2019") %>%
  filter(flat_type == "4 ROOM") %>%
  group_by(full_address,latitude_list_full,longitude_list_full,closest_MRT,closest_distance, CBD_dist)  %>% 
  summarize("Median Price" = median(resale_price), "Volume" = n(), "Median Area"=median(floor_area_sqm),"Median Lease Start Date"=median(lease_commence_date))
head(resale_loglat_4room_2019)
```



```{r}
packages = c('ggplot2','readr','sf','tmap','dplyr', 'tidyr','stringr','leaflet','leaflet.extras')
for (p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
  }
  library(p,character.only = T)
}
#resale
resale_loglat <-read_csv("data/HDB Resale data final.csv")
resale_loglat_4room_2019 <-resale_loglat %>% 
  mutate(year=substr(month, start = 1, stop = 4)) %>%
  mutate(full_address=str_to_title(full_address)) %>%
  filter(latitude_list_full != 0) %>%
  filter(year == "2019") %>%
  filter(flat_type == "4 ROOM") %>%
  group_by(full_address,latitude_list_full,longitude_list_full,closest_MRT,closest_distance, CBD_dist)  %>% 
  summarize("Median Price" = median(resale_price), "Volume" = n(), "Median Area"=median(floor_area_sqm),"Median Lease Start Date"=median(lease_commence_date))

#mrt
mrt <-read_csv("data/MRT with Location.csv")
mrt_icon<- makeIcon(iconUrl = "AWT-Train.png",iconWidth = 6, iconHeight = 6)

#map
min = min(resale_loglat_4room_2019$`Median Price`)
max = max(resale_loglat_4room_2019$`Median Price`)
bins=c(200000,400000,600000,800000,1000000,1200000)
pal = colorBin(palette = "Reds", domain = c(min, max),bins=bins)
leaflet() %>%   addTiles(group = "OpenStreetMap") %>%
  addProviderTiles("CartoDB.Positron", group = "CartoDB.Positron") %>%
  addProviderTiles("Esri.WorldTopoMap", group = "Esri.WorldTopoMap") %>%
  setView(lng = 103.845, lat = 1.34, zoom = 11) %>%
  addCircleMarkers(data=resale_loglat_4room_2019, 
                   lng= ~longitude_list_full, 
                   lat= ~latitude_list_full, 
                   radius = 1, 
                   color = ~pal(resale_loglat_4room_2019$`Median Price`),
                   opacity= 0.5,
                   popup = paste("Address: ", resale_loglat_4room_2019$full_address, "<br>", 
                                 "Median Area (sqm): ", resale_loglat_4room_2019$`Median Area`, "<br>",
                                 "Median Price (S$): ", format(round(resale_loglat_4room_2019$`Median Price`,digits=2),nsmall=2,big.mark=","), "<br>",
                                 "Median Lease Start Date: ", resale_loglat_4room_2019$`Median Lease Start Date`, "<br>",
                                 "Closest Mrt: ", resale_loglat_4room_2019$closest_MRT, "<br>",
                                 "Distance from Mrt (m): ", format(round(resale_loglat_4room_2019$closest_distance,digits=2),nsmall=2,big.mark=","), "<br>",
                                 "Distance from CBD (m): ", format(round(resale_loglat_4room_2019$CBD_dist,digits=2),nsmall=2,big.mark=",")),
                                  group = "circles") %>%
   addMarkers(data=mrt,
              lng=~longitude_list, 
              lat=~latitude_list, 
              icon = mrt_icon,
              label = mrt$`MRT.MRT_station`,group = 'markers') %>%
   addLayersControl(baseGroups = c("CartoDB.Positron","OpenStreetMap","Esri.WorldTopoMap"), 
                    options = layersControlOptions(collapsed = TRUE)) %>%
   addLegend(data=resale_loglat_4room_2019,
             pal=pal,
             values = ~`Median Price`,
             position = "bottomright",
             title ="Median Price (S$)"
  )%>%
  addSearchFeatures(
    targetGroups = 'markers', # group should match addMarkers() group
    options = searchFeaturesOptions(
      zoom=14, openPopup = TRUE, firstTipSubmit = TRUE,
      autoCollapse = TRUE, hideMarkerOnCollapse = TRUE
    )
  )
```




